$('.top-slide').owlCarousel({
    animateOut: 'fadeOut',
    items:1,
    smartSpeed:2200,
    loop:true,
    margin:0,
    autoplay:true,
    autoplayHoverPause:false,
    nav:true,
    autoplayTimeout:5000,
    navText : ['<i class="fas fa-caret-left"></i>','<i class="fas fa-caret-right"></i>'],
}),
$('.top-slide-mob').owlCarousel({
    animateOut: 'fadeOut',
    items:1,
    smartSpeed:2200,
    loop:true,
    margin:0,
    autoplay:true,
    autoplayHoverPause:false,
    nav:true,
    autoplayTimeout:5000,
    navText : ['<i class="fas fa-caret-left"></i>','<i class="fas fa-caret-right"></i>'],
}),
$('.create-slide').owlCarousel({
    animateOut: 'fadeOut',
    items:1,
    smartSpeed:2200,
    loop:true,
    margin:0,
    autoplay:true,
    autoplayHoverPause:false,
    nav:true,
    autoplayTimeout:5000,
    navText : ['<i class="fas fa-caret-left"></i>','<i class="fas fa-caret-right"></i>'],
})